CREATE TABLE Topics(
	TopicID INT IDENTITY(1,1) PRIMARY KEY, 
	Theme VARCHAR(100) NOT NULL,
	Content VARCHAR(500) NOT NULL,
	CreateUser VARCHAR(50) CONSTRAINT DF_Topic_CreateUser DEFAULT ORIGINAL_LOGIN(),
    CreateDate DATETIME CONSTRAINT DF_Topic_CreateDate DEFAULT GETDATE(),
    LastUpdateUser VARCHAR(50) NULL,
    LastUpdateDate DATETIME NULL
);
